In [1]:
import math
print("it's a math! It has type{}".format(type(math)))

it's a math! It has type<class 'module'>


math is a module. A module is just a collection of variables (a namespace, if you like) defined by someone else. We can see all the names in math using the built-in function dir().

In [2]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [3]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [5]:
math.log(32,2)
# 2*2*2*2*2

5.0

In [6]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [8]:
import numpy
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([4, 5, 2, 5, 4, 3, 4, 4, 2, 4])

In [9]:
type(rolls)

numpy.ndarray

In [11]:
#maybe I just want to turn the array into a list, in which case I can use "tolist"
rolls.tolist()

[4, 5, 2, 5, 4, 3, 4, 4, 2, 4]

In [12]:
rolls + 10

array([14, 15, 12, 15, 14, 13, 14, 14, 12, 14])

In [13]:
rolls <=3

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [15]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\n x =\n{}".format(xlist, x))


xlist = [[1, 2, 3], [2, 4, 6]]
 x =
[[1 2 3]
 [2 4 6]]


In [16]:
x[1,-1] #1= columnnumber, -1 is last element

6

In [17]:
import tensorflow as tf

In [18]:
a = tf.constant(1)
b = tf.constant(1)
c =a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=2>

a symbolic handle to one of the outputs of an Operation. It does not hold the values of that operation's output, but instead provides a means of computing those values in a TensorFlow tf.Session.